# Generated by Django 5.2.2 on 2025-06-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='location',
            new_name='emplacement',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='titre',
        ),
    ]
